"""add category to searches

Revision ID: 120604f077fb
Revises: 50028b2596f2
Create Date: 2026-08-23 13:12:39.160156

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "120604f077fb"
down_revision: Union[str, Sequence[str], None] = "50028b2596f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "searches",
        sa.Column(
            "category_id",
            sa.String(length=20),
            nullable=True,
            comment="Resolved eBay leaf category for compatibility_filter; NULL = fallback query-enrichment mode",
        ),
    )
    op.add_column(
        "searches",
        sa.Column(
            "category_name",
            sa.String(length=100),
            nullable=True,
            comment="Display name of the resolved category",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("searches", "category_name")
    op.drop_column("searches", "category_id")
    # ### end Alembic commands ###
