"""add nhtsa model cache

Revision ID: 27d3dcc8a334
Revises: cf2692058fc6
Create Date: 2026-08-26 09:01:54.690471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d3dcc8a334'
down_revision: Union[str, Sequence[str], None] = 'cf2692058fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nhtsa_model_cache',
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('models_json', sa.Text(), nullable=False, comment='JSON array of model names'),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('make', 'year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nhtsa_model_cache')
    # ### end Alembic commands ###
