"""Initial schema: all tables from SYSTEM_CONTEXT Section 7

Revision ID: 862710ad10dd
Revises: 
Create Date: 2026-04-21 19:47:33.457115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862710ad10dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cycle_type', sa.String(length=20), nullable=False, comment='nightly | intraday | manual'),
    sa.Column('searches_processed', sa.Integer(), nullable=False),
    sa.Column('listings_fetched', sa.Integer(), nullable=False),
    sa.Column('listings_new', sa.Integer(), nullable=False),
    sa.Column('listings_updated', sa.Integer(), nullable=False),
    sa.Column('api_calls_made', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='running | completed | failed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ebay_item_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Current price (Decimal)'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('seller_name', sa.String(length=100), nullable=True),
    sa.Column('seller_feedback_score', sa.Integer(), nullable=True),
    sa.Column('seller_feedback_pct', sa.Numeric(precision=5, scale=2), nullable=True, comment='Seller positive feedback percentage'),
    sa.Column('item_url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('ebay_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category_id', sa.String(length=20), nullable=True),
    sa.Column('compatibility_checked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_ebay_item_id'), 'listings', ['ebay_item_id'], unique=True)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='ebay'),
    sa.Column('access_token', sa.Text(), nullable=False, comment='Stored as plaintext in Phase 1; encrypt in Phase 2+'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxonomy_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.String(length=20), nullable=False),
    sa.Column('marketplace', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('trim', sa.String(length=100), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'marketplace', 'year', 'make', 'model', name='uq_taxonomy_entry')
    )
    op.create_index(op.f('ix_taxonomy_cache_category_id'), 'taxonomy_cache', ['category_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True, comment='External Clerk/Auth0 ID'),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False, comment='free | pro'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active | disabled'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vin_decode_cache',
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('trim', sa.String(length=100), nullable=True),
    sa.Column('body_class', sa.String(length=100), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('decoded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('vin')
    )
    op.create_table('api_quota_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Nullable for system-level calls'),
    sa.Column('provider', sa.String(length=30), nullable=False, comment='ebay_browse | ebay_taxonomy | nhtsa'),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_quota_log_user_id'), 'api_quota_log', ['user_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Snapshot price (Decimal)'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_listing_id'), 'price_history', ['listing_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('trim', sa.String(length=100), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_table('searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('oem_number', sa.String(length=50), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Maximum price filter (Decimal)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_high_priority', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searches_user_id'), 'searches', ['user_id'], unique=False)
    op.create_index(op.f('ix_searches_vehicle_id'), 'searches', ['vehicle_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False, comment='price_drop | new_listing'),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='email | none'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_listing_id'), 'alerts', ['listing_id'], unique=False)
    op.create_index(op.f('ix_alerts_search_id'), 'alerts', ['search_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('search_listings',
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('search_id', 'listing_id'),
    sa.UniqueConstraint('search_id', 'listing_id', name='uq_search_listing')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_listings')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_search_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_listing_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_searches_vehicle_id'), table_name='searches')
    op.drop_index(op.f('ix_searches_user_id'), table_name='searches')
    op.drop_table('searches')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_price_history_listing_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_api_quota_log_user_id'), table_name='api_quota_log')
    op.drop_table('api_quota_log')
    op.drop_table('vin_decode_cache')
    op.drop_table('users')
    op.drop_index(op.f('ix_taxonomy_cache_category_id'), table_name='taxonomy_cache')
    op.drop_table('taxonomy_cache')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_listings_ebay_item_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_table('fetch_runs')
    # ### end Alembic commands ###
