"""add compat_value_cache

Revision ID: b70b7de84943
Revises: 27d3dcc8a334
Create Date: 2026-09-14 13:19:33.257089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70b7de84943'
down_revision: Union[str, Sequence[str], None] = '27d3dcc8a334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compat_value_cache',
    sa.Column('property', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.String(length=20), nullable=False),
    sa.Column('filter_make', sa.String(length=100), nullable=False),
    sa.Column('marketplace', sa.String(length=20), nullable=False),
    sa.Column('values_json', sa.Text(), nullable=False, comment='JSON array of canonical values'),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('property', 'category_id', 'filter_make', 'marketplace')
    )
    # NOTE: autogenerate also proposed a uq_search_listing constraint on
    # search_listings — pre-existing model/DB drift unrelated to this
    # change; deliberately excluded.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compat_value_cache')
    # ### end Alembic commands ###
