"""add listing aspects

Revision ID: cf2692058fc6
Revises: e710aab2051a
Create Date: 2026-08-25 11:40:33.350194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2692058fc6'
down_revision: Union[str, Sequence[str], None] = 'e710aab2051a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('brand', sa.String(length=100), nullable=True, comment='eBay Item Specifics Brand aspect'))
    op.add_column('listings', sa.Column('mpn', sa.String(length=100), nullable=True, comment='Manufacturer Part Number aspect'))
    op.add_column('listings', sa.Column('oe_part_number', sa.String(length=100), nullable=True, comment='OE/OEM Part Number aspect (verbatim)'))
    op.add_column('listings', sa.Column('aspects_fetched_at', sa.DateTime(timezone=True), nullable=True, comment='When getItem aspects lookup succeeded; NULL = pending/retry'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'aspects_fetched_at')
    op.drop_column('listings', 'oe_part_number')
    op.drop_column('listings', 'mpn')
    op.drop_column('listings', 'brand')
    # ### end Alembic commands ###
