"""add relevance to search_listings

Revision ID: e710aab2051a
Revises: 120604f077fb
Create Date: 2026-08-24 13:56:20.364668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e710aab2051a'
down_revision: Union[str, Sequence[str], None] = '120604f077fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_listings', sa.Column('relevance', sa.String(length=10), nullable=True, comment='AI verdict: part | accessory | unrelated; NULL = unclassified'))
    op.add_column('search_listings', sa.Column('relevance_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_listings', 'relevance_checked_at')
    op.drop_column('search_listings', 'relevance')
    # ### end Alembic commands ###
