"""Curated consumer makes for the vehicle form dropdown.

NHTSA's full registry has 10,000+ entries (trailer/coachbuilders) — a
useless dropdown. Values match NHTSA naming; the URL path lookup is
case-insensitive. Free-text fallback covers anything missing here.
"""

COMMON_MAKES: tuple[str, ...] = (
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Fisker",
    "Ford",
    "Genesis",
    "GMC",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Isuzu",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "Lucid",
    "Maserati",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "Mercury",
    "MINI",
    "Mitsubishi",
    "Nissan",
    "Oldsmobile",
    "Plymouth",
    "Polestar",
    "Pontiac",
    "Porsche",
    "RAM",
    "Rivian",
    "Rolls-Royce",
    "Rover",
    "Saab",
    "Saturn",
    "Scion",
    "Smart",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
)
